apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: telge-dev

patches:
  - path: simulator.yaml
  - path: visualisation.yaml
  - path: sampleAddresses.yaml
