apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-address-ingress
spec:
  tls:
    - hosts:
        - streams.dev.telge.iteam.pub
      secretName: sampleaddresses-dev-tls
  rules:
    - host: streams.dev.telge.iteam.pub
      http:
        paths:
          - path: /addresses/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: sample-address
                port:
                  number: 4001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-address
spec:
  template:
    spec:
      containers:
        - name: sample-address
          env:
            - name: PELIAS_HOSTNAME
              value: http://elastic-dev-elasticsearch.elasticsearch-dev.svc.cluster.local:9200
