apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-address-ingress
spec:
  tls:
    - hosts:
        - streams.dev.telge.iteam.pub
      secretName: sampleaddresses-dev-tls
  rules:
    - host: streams.dev.telge.iteam.pub
      http:
        paths:
          - path: /addresses/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: sample-address
                port:
                  number: 4001
