apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: visualisation-ingress
spec:
  tls:
    - hosts:
        - dev.telge.iteam.pub
      secretName: telge-dev-tls
  rules:
    - host: dev.telge.iteam.pub
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: visualisation
                port:
                  number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visualisation
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    spec:
      containers:
        - name: visualisation
          image: ghcr.io/predictivemovement/telge-twin-visualisation:dev-20260220152309-5055381 # {"$imagepolicy": "flux-system:visualisation-dev"}
          imagePullPolicy: Always
